- hosts: NODES
  
  order: sorted

  tasks:

    - name: Update Apt Cache
      apt:
        update_cache: yes
      become: yes
      become_method: su

    - name: Install Htop
      apt:
        name: htop
        state: latest
      become: yes
      become_method: su
      
     - name: Install tshark
      apt:
        name: tshark
        state: latest
      become: yes
      become_method: su
      
    - name: Install resolvconf
      apt:
        name: resolvconf
        state: latest
      become: yes
      become_method: su
      
    - name: Install tcpdump
      apt:
        name: tcpdump
        state: latest
      become: yes
      become_method: su      
